name: Build

on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      # 
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      # 
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Get dependencies
        env:
          GOPROXY: "https://proxy.golang.org"
        run: |
          go get -v -t -d ./...

      - name: Build
        run: go build -v .

      - name: Test
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go test -v .